### ISSUE TITLE
Dataframe not reading embedded JSON primitive

### ISSUE THREAD

**Issue by iamsteveholmes** [Kotlin/dataframe#122]
Hey folks!  A picture is worth a thousand words on this one:

<img width="1165" alt="Screen Shot 2022-06-24 at 10 25 06 AM" src="https://user-images.githubusercontent.com/92353/175612216-dbff1e4c-bce8-4b43-931e-000fcc3eebbc.png">

I first noticed this when reading a file but I simplified to the most simple example.  It's a pity as the functionality is otherwise amazing.

**Comment by koperagen** [comment]
Hi! Thank you for the report. I'll fix it on monday and let you know when the fix is published. Meanwhile, if you need a workaround, rename field from "value" (or also "array") to anything else in that JSON

**Comment by iamsteveholmes** [comment]
...ohhhh is that the issue?  The problem is that I'm parsing hundreds of files and I don't get to decide the names of fields...

**Comment by koperagen** [comment]
yeah. You see, right now if a json array has mixed values (record and arrays, records and literal values) we save it as ColumnGroup with record fields + "value" field with all literal values and "array" field with all arrays. 
https://github.com/Kotlin/dataframe/blob/a0b9d49d75fb7dff6fae1f99da1203367fefe9d7/tests/src/test/kotlin/org/jetbrains/kotlinx/dataframe/api/parse.kt#L39

Due to a bug in this logic, our parsing treats field with those names in the wrong way. So, for now, I can only suggest to wait for the fix :)

**Comment by koperagen** [comment]
Hi! Fix is published: `0.8.0-dev-1055`

**Comment by iamsteveholmes** [comment]
> 

Beautiful!  I've got it working in my notebook.  Thanks for the great work!
