### ISSUE TITLE
Class from `implementation` dependency in public API

### ISSUE THREAD

**Issue by koperagen** [Kotlin/dataframe#218]
If i try to call `readOpenApi` in a project with just `implementation("org.jetbrains.kotlinx:dataframe-openapi:0.9.1")`

i get
```
Cannot access class 'io.swagger.v3.parser.core.models.ParseOptions'. Check your module classpath for missing or conflicting dependencies
```

**Comment by Jolanrensen** [comment]
Can reproduce. 
Solved by changing `implementation(libs.swagger)` to `api(libs.swagger)` in build.gradle.kts of openapi module. 
In the meantime, if you want to use this function directly (instead of using the ksp/gradle/jupyter plugins), add `implementation("io.swagger.parser.v3:swagger-parser:2.1.2")` to your gradle file.

**Comment by Jolanrensen** [comment]
also, add `project(":dataframe-openapi")` to the dataframe module, so it will be imported by default when a user tries to implement dataframe
