### ISSUE TITLE
Output resizable table in Jupyter notebooks

### ISSUE THREAD

**Issue by alllex** [Kotlin/dataframe#219]
Currently, if dataframe cells contain text that is longer than a specific length, it gets truncated without the possibility to view the whole values. This makes it really hard to work with such dataframes.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/2759152/212364001-277083a1-3af2-4f17-8275-7af74d605f3a.png">

If it's not possible or too involved to create resizable tables, then there should at least be a workaround to be able to adjust the width of the columns from the code.

**Comment by alllex** [comment]
After some digging I found the answer and submitted a PR to improve the docs in this regard:
* https://github.com/Kotlin/dataframe/pull/220

**Comment by koperagen** [comment]
It's not the best, but you can hold mouse over cell and it should show tooltip with it's content. 
I think the issue is worth keeping open until it's actually adressed. With interactive widget that are now supported in notebooks it should be possible to make dataFrameConfig.display adjustable. We might implement it way sooner than proper rendering of hierarhical tables in IntelliJ
