### ISSUE TITLE
Known issues with Collection of Java classes

### ISSUE THREAD

**Issue by zaleslaw** [Kotlin/dataframe#380]

**Comment by zaleslaw** [comment]
@belovrv could you share some details here and give some code snippets?

**Comment by zaleslaw** [comment]
@belovrv

**Comment by zaleslaw** [comment]
@belovrv

**Comment by belovrv** [comment]
Repro: I have a Java class like this:
``` java
public class Item {
    private final int val;
    public Item(int value) {
        val = value;
    }

    int getValue() {
        return val;
    }
}
```

And following Kotlin code:
``` kotlin
class Item1(val value: Int)

data class Container(val item: Item, val item1: Item1)

fun main() {
    val arr = listOf(
        Container(Item(1), Item1(1)),
        Container(Item(2), Item1(3)),
        Container(Item(3), Item1(3))
        )
    println("${arr[0].item.value}, ${arr[0].item1.value}")

    println(arr.toDataFrame(maxDepth = 2).toString())

}
```

The output is
```
1, 1
   item       item1
 0  { } { value:1 }
 1  { } { value:3 }
 2  { } { value:3 }
```
But expected that java property will be traversed by `toDataFrame` as well.

**Comment by Jolanrensen** [comment]
Java class traversing could be possible by scanning functions starting with 
"get" or "is" using reflection. This is similar to how the [Java Bean encoder from Spark](https://spark.apache.org/docs/latest/api/java/org/apache/spark/sql/Encoders.html#bean(java.lang.Class)) scans Java 'data' classes.

Not that difficult, but it requires some research. Might look into it because it does sound fun
