### ISSUE TITLE
`"" + columnRef` becomes `String` 

### ISSUE THREAD

**Issue by sorokod** [Kotlin/dataframe#750]
Sample code (version 0.12.0):

```kotlin
    val df1 = dataFrameOf("name", "age")(
        "Alice", 15,
        "Bob", 20,
        "Charlie", 100
    )

    val name  by column<String>()
    val name_age by column<String>()

    df1.add(name_age) { name + "!!!" }.also { println(it) }
    df1.add(name_age) { "!!!" + name  }.also { println(it) }
```
The first println (`name + "!!!"`) produces:
```
      name age   name_age
 0   Alice  15   Alice!!!
 1     Bob  20     Bob!!!
 2 Charlie 100 Charlie!!!
```
The second println (` "!!!" + name`) produces:
```
      name age                                 name_age
 0   Alice  15 !!!org.jetbrains.kotlinx.dataframe.im...
 1     Bob  20 !!!org.jetbrains.kotlinx.dataframe.im...
 2 Charlie 100 !!!org.jetbrains.kotlinx.dataframe.im...
```
The root cause is that In the two example `+` resolves to different functions. A foot gun that should be fixed.

**Comment by Jolanrensen** [comment]
It should indeed be fixed but unfortunately we can't. It's a language limitation.

Have you tried making a function like `operator fun String.plus(something)`? 
![image](https://github.com/Kotlin/dataframe/assets/17594275/98610578-dc54-48ff-ac1a-d654259da4d7)
Since `String` already has a function `plus`, an extension function overload will never be called by default.

**Comment by sorokod** [comment]
I would consider deprecating, and ultimately removing  `public operator fun ColumnReference<String>.plus`.
