### ISSUE TITLE
Improve and document CSV reading options 

### ISSUE THREAD

**Issue by koperagen** [Kotlin/dataframe#787]
https://youtrack.jetbrains.com/issue/KT-69798
Unlike readCSV, readDelim exposes underlying apache common CSVFormat. There're a lot more configuration options. From the linked issue it seems arguments that readCSV provide are not enough to read every possible kind of file. 
So at least readDelim needs documentation here
https://kotlin.github.io/dataframe/read.html
Or readCSV should have more options. But, i'd avoid exposing CSVFormat in readCSV

**Comment by zaleslaw** [comment]
We agreed to split the issue
- answer the use-case
- provide a default

**Comment by unrec** [comment]
Thanks everyone for working on this issue.

I agree that exposing `CSVFormat` to `readCSV` fun is not good, but there should be a flexibility in CSV setup configuration.
I faced it with a .csv file with quote character in some row, so as I understand there are 2 possible options:
- be able to set specific quote character instead of `"`
- have an opportunity to disable quote char completely

This should be added as a optional param to `readCsv` fun instead of `readDelim`.

**Comment by Jolanrensen** [comment]
Will be solved by the new CSV implementation: "dataframe-csv". Setting a quote character is supported by default.

The new read functions will also expose a single overload where you can adjust additional `CsvSpecs` if we ever miss out on a parameter in the future.
