### ISSUE TITLE
Make Kotlin Datetime Optional

### ISSUE THREAD

**Issue by hantsy** [Kotlin/dataframe#892]
Given an example like this. 

```kotlin
data class (
   @ColumnName("Start")
   val startedTime:LocalTime // java 8 DateTime
)
```
Which works well in the previous version.

When upgrading to 0.14, I got the exception like:

```bash 
Type converter from kotlinx.datetime.LocalTime to java.time.LocalTime? is not found for column
```

Now I have to add a manual convert to make it work. 

```kotlin
   dataFrame
   .convert{ "Start"<kotlinx.datetime.LocalTime>()}.with{
        it.toJavaLocalTime()
   }
   
```
 
Even though we are using Kotlin in our backend, Java 8 Datetime is more popular than Kotlin DateTime. 

We do not want to introduce more dependencies that we do not use.

_Originally posted by @hantsy in https://github.com/Kotlin/dataframe/discussions/887#discussioncomment-10773985_

It is better to support Java 8 Datetime by default, and make Kotlinx datetime optional for dataframe-core.

**Comment by Jolanrensen** [comment]
Specific issue can be solved by fixing https://github.com/Kotlin/dataframe/issues/894.

**Comment by hantsy** [comment]
The conversion is resolved, but I hope to introduce fewer deps in projects.

**Comment by Jolanrensen** [comment]
@hantsy I think it makes sense for DataFrame to have kotlinx dependencies, as DataFrame itself is kotlinx after all. If DataFrame ever hopes to go multiplatform, we'll have to use kotlinx datetime and kotlinx serialization instead of java-specific libraries anyways. Of course, we'll still support java specific types, like `java.time.*`, but they won't be the default type. Similarly, if Kotlin ever introduces their own BigDecimal and BigInteger, we'll make those the default, instead of the Java ones.

At the same time, we indeed also strive to have fewer dependencies in the project, to shrink the core module. This we try to do by moving integration components to optional modules. It's a bit time-consuming though, as many components have become interwoven with each other. But, to give an example, we're in the progress of extracting CSV (and its dependencies), we split the OpenAPI module in two (OpenAPI is already optional, but now it's split into a runtime component and a gradle plugin dependency, shrinking the shipped jar further), and we were trying to extract the Jupyter/notebooks integration from the core too.
