### ISSUE TITLE
Support digit grouping separators on import

### ISSUE THREAD

**Issue by belovrv** [Kotlin/dataframe#9]
Support numbers like 1,593.23 or 10 233 000 etc
See: https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html

**Comment by Jolanrensen** [comment]
We have support for `java.text.NumberFormat` locales. In my tests, it appears locales seem to work fine as long as there are no spaces in the number. This appears to be a limitation of `NumberFormat` as of now but might be fixed in newer Java versions.

Example:
```kotlin
val df = dataFrameOf("a")("4.294.967.295,000", "4.294.967.295,000", "4.294.967.295,000")
    .convert { column<String>("a") }.to {
        it.convertToDouble(Locale.GERMAN)
    }

df.print(columnTypes = true, title = true, borders = true)
//    ⌌--------------⌍
//    |  |   a:Double|
//    |--|-----------|
//    | 0| 4294967295|
//    | 1| 4294967295|
//    | 2| 4294967295|
//    ⌎--------------⌏
```

Locale is also an option anytime `ParseOptions` are available, which appears to be in TSV, CSV reading etc.

Closing for now :)
