### ISSUE TITLE
Trivial JsonPath Traversal Failing

### ISSUE THREAD

**Issue by neilchaudhuri** [Kotlin/dataframe#974]
I am trying to get the hang of JsonPath. I have a fairly trivial top-level JSON structure like this:

<img width="319" alt="Screenshot 2024-11-27 at 12 20 49 PM" src="https://github.com/user-attachments/assets/d23195a7-cbf8-4631-8eb5-0c2bc15d5960">

When I do `JsonPath().append("Blocks")` I get this:

`Key value path JsonPath(path=$["Blocks"]) does not match objects. `

Can you tell me how I am misusing JsonPath?

**Comment by Jolanrensen** [comment]
Hi! 

I suspect it's because you're pointing at an array, not at objects.

The `keyValuePaths` argument in `readJson` functions is there to convert JSON objects you target to two columns: "key" and "value", instead of making each key in the objects a column and each value its contents.

If you want to convert each object in `Blocks`, you need to make the JsonPath look like `$["Blocks"]["*"]`, so something like `JsonPath().append("Blocks").appendArrayWithWildcard()` should work :).

**Comment by neilchaudhuri** [comment]
Thanks!
